### PR TITLE
Jesus's work on html template

### PR DESCRIPTION
**Pull request by jepetty**
Use the index as a skeleton to model other pages

### CODE REVIEW

**Comment by jepetty** [comment]
@jeor0980 can we remove the example.html file?

**Comment by jeor0980** [comment]
Yep, must of forgotten about it

**Comment by jepetty** [comment]
👍  lgtm

**Comment by jepetty** [comment]
I WANT TO MERGE HELPPPP

**Review by jepetty — COMMENTED** [review]
You've already done what i wanted lgtm

**Review by jeor0980 — APPROVED** [review]

**Pull request merged**
